import uvicorn
import os
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles
from fastapi.responses import FileResponse
from backend.models.api_models import ChatRequest, ChatResponse
from backend.services.gemini_service import GeminiService

app = FastAPI(
    title="Proxi Backend",
    description="Backend API for Proxi Headless Operator",
    version="0.1.0"
)

# Initialize Service
gemini_service = GeminiService()

# CORS Configuration
origins = [
    "http://localhost:5173",  # Vite default
    "http://localhost:3000",  # React default
    "*"                       # Allow all for development
]

app.add_middleware(
    CORSMiddleware,
    allow_origins=origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.get("/api/health")
async def health_check():
    return {"message": "Proxi System Online", "status": "operational"}

@app.post("/api/chat", response_model=ChatResponse)
async def chat(request: ChatRequest):
    """
    Endpoint to interact with Gemini via the Backend Service.
    Supports tiered compute via the 'complexity' parameter.
    """
    try:
        response_text = ""
        model_used = ""

        # Tiered Compute Routing
        if request.complexity == "deep":
            response_text = await gemini_service.generate_deep_thought(request.message)
            model_used = gemini_service.SMART_TEXT_MODEL
        else:
            # Default to "fast" / reflex
            response_text = await gemini_service.generate_reflex_response(request.message)
            model_used = gemini_service.FAST_TEXT_MODEL

        return ChatResponse(
            response=response_text,
            status="success",
            model_used=model_used
        )
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

# --- Static File Serving (React App) ---
# In production (Docker), the 'dist' folder is copied to 'backend/static'
static_dir = os.path.join(os.path.dirname(__file__), "static")

if os.path.exists(static_dir):
    # Mount the assets folder (CSS/JS generated by Vite)
    assets_dir = os.path.join(static_dir, "assets")
    if os.path.exists(assets_dir):
        app.mount("/assets", StaticFiles(directory=assets_dir), name="assets")

    # Catch-all route for SPA (Single Page Application)
    @app.get("/{full_path:path}")
    async def serve_spa(full_path: str):
        file_path = os.path.join(static_dir, full_path)
        if os.path.exists(file_path) and os.path.isfile(file_path):
            return FileResponse(file_path)
        return FileResponse(os.path.join(static_dir, "index.html"))

if __name__ == "__main__":
    uvicorn.run("backend.main:app", host="0.0.0.0", port=8000, reload=True)