server {
    listen 80;
    server_name proxi.audista.com; 

    # Frontend (Vite HMR + WebSockets)
    # Proxies to Docker container exposed on port 4001
    location / {
        proxy_pass http://localhost:4001;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
    }

    # Backend (API)
    # Proxies to Docker container exposed on port 4000
    location /api/ {
        proxy_pass http://localhost:4000/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
