#!/bin/bash
# Proxi Frontend Deployment Script for Oracle Cloud Ubuntu
# Run on the Ubuntu A1.Flex server (proxi.audista.com)

set -e

echo "=== PROXI Frontend Deployment ==="
echo "Started at: $(date)"

# Configuration
DEPLOY_DIR="/var/www/proxi"
NGINX_CONF="/etc/nginx/sites-available/proxi"
DOMAIN="proxi.audista.com"
BACKEND_TAILSCALE_IP="${BACKEND_IP:-100.100.100.2}"  # Set via env or default

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

log_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# Check if running as root or with sudo
if [ "$EUID" -ne 0 ]; then
    log_error "Please run as root or with sudo"
    exit 1
fi

# Step 1: Update system
log_info "Updating system packages..."
apt update && apt upgrade -y

# Step 2: Install dependencies
log_info "Installing dependencies..."
apt install -y nginx nodejs npm certbot python3-certbot-nginx curl git

# Check Node.js version
NODE_VERSION=$(node -v 2>/dev/null || echo "none")
log_info "Node.js version: $NODE_VERSION"

if [[ "$NODE_VERSION" == "none" ]] || [[ "${NODE_VERSION:1:2}" -lt 18 ]]; then
    log_warn "Node.js version too old, installing Node 20..."
    curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
    apt install -y nodejs
fi

# Step 3: Clone or update repository
log_info "Setting up application directory..."
if [ -d "$DEPLOY_DIR/.git" ]; then
    log_info "Updating existing repository..."
    cd $DEPLOY_DIR
    git fetch origin
    git reset --hard origin/main
else
    log_info "Cloning repository..."
    mkdir -p $DEPLOY_DIR
    # For hackathon, copy files from local or use git
    # git clone https://github.com/yourusername/proxi-ai.git $DEPLOY_DIR
    log_warn "Please manually copy or clone the repository to $DEPLOY_DIR"
fi

# Step 4: Build frontend
log_info "Building frontend..."
cd $DEPLOY_DIR/frontend

# Create production environment file
cat > .env.production <<EOF
VITE_API_URL=
VITE_WS_URL=wss://${DOMAIN}
EOF

npm install
npm run build

# Step 5: Deploy to nginx
log_info "Deploying to nginx..."
rm -rf /var/www/html/proxi
cp -r dist /var/www/html/proxi

# Step 6: Configure nginx
log_info "Configuring nginx..."
cat > $NGINX_CONF <<EOF
# Proxi Frontend + API Proxy Configuration
# Generated by deploy-frontend.sh on $(date)

# Rate limiting zone
limit_req_zone \$binary_remote_addr zone=api_limit:10m rate=30r/m;
limit_req_zone \$binary_remote_addr zone=login_limit:10m rate=5r/m;

# HTTP -> HTTPS redirect
server {
    listen 80;
    listen [::]:80;
    server_name ${DOMAIN};
    return 301 https://\$server_name\$request_uri;
}

# Main HTTPS server
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name ${DOMAIN};

    # SSL configuration (will be updated by certbot)
    ssl_certificate /etc/letsencrypt/live/${DOMAIN}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/${DOMAIN}/privkey.pem;
    ssl_session_timeout 1d;
    ssl_session_cache shared:SSL:50m;
    ssl_session_tickets off;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256;
    ssl_prefer_server_ciphers off;

    # Security headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;

    # Frontend static files
    root /var/www/html/proxi;
    index index.html;

    # SPA routing - try files, then index.html
    location / {
        try_files \$uri \$uri/ /index.html;
    }

    # API proxy to backend (via Tailscale)
    location /api {
        # Rate limiting
        limit_req zone=api_limit burst=10 nodelay;
        
        proxy_pass http://${BACKEND_TAILSCALE_IP}:8080;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        
        # Timeout settings for long-running requests
        proxy_connect_timeout 60s;
        proxy_send_timeout 300s;
        proxy_read_timeout 300s;
        
        # Buffer settings
        proxy_buffering off;
        proxy_buffer_size 4k;
    }

    # Stricter rate limit for login
    location /api/auth/login {
        limit_req zone=login_limit burst=3 nodelay;
        
        proxy_pass http://${BACKEND_TAILSCALE_IP}:8080;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
    }

    # Health check endpoint (no rate limit)
    location /api/health {
        proxy_pass http://${BACKEND_TAILSCALE_IP}:8080;
        proxy_http_version 1.1;
    }

    # Gzip compression
    gzip on;
    gzip_vary on;
    gzip_min_length 1024;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml;
}
EOF

# Enable site
ln -sf $NGINX_CONF /etc/nginx/sites-enabled/proxi

# Remove default site if exists
rm -f /etc/nginx/sites-enabled/default

# Test nginx config
log_info "Testing nginx configuration..."
nginx -t

# Reload nginx
systemctl reload nginx

# Step 7: SSL certificate
log_info "Setting up SSL certificate..."
if [ ! -f "/etc/letsencrypt/live/${DOMAIN}/fullchain.pem" ]; then
    certbot --nginx -d ${DOMAIN} --non-interactive --agree-tos -m admin@${DOMAIN} || {
        log_warn "Certbot failed. You may need to run it manually."
        log_warn "Command: certbot --nginx -d ${DOMAIN}"
    }
else
    log_info "SSL certificate already exists"
    certbot renew --dry-run
fi

# Step 8: Tailscale check
log_info "Checking Tailscale status..."
if command -v tailscale &> /dev/null; then
    TAILSCALE_STATUS=$(tailscale status 2>&1 || echo "not connected")
    log_info "Tailscale: $TAILSCALE_STATUS"
else
    log_warn "Tailscale not installed. Install with:"
    log_warn "  curl -fsSL https://tailscale.com/install.sh | sh"
    log_warn "  sudo tailscale up"
fi

# Done
echo ""
log_info "=== Deployment Complete ==="
echo ""
echo "Frontend URL: https://${DOMAIN}"
echo "Backend IP:   ${BACKEND_TAILSCALE_IP}:8080"
echo ""
echo "Next steps:"
echo "1. Ensure Tailscale is connected: tailscale status"
echo "2. Update BACKEND_IP if needed: BACKEND_IP=x.x.x.x ./deploy-frontend.sh"
echo "3. Test the deployment: curl https://${DOMAIN}/api/health"
echo ""
