# Proxi Backend Deployment Script for Windows Server
# Run as Administrator in PowerShell

param(
    [string]$ProxiDir = "C:\Proxi",
    [string]$GeminiApiKey = "",
    [switch]$InstallTailscale,
    [switch]$InstallVirtualDisplay,
    [switch]$CreateService
)

$ErrorActionPreference = "Stop"

Write-Host "=== PROXI Backend Deployment ===" -ForegroundColor Green
Write-Host "Started at: $(Get-Date)" -ForegroundColor Gray

# Helper functions
function Write-Step { param($Message) Write-Host "[STEP] $Message" -ForegroundColor Cyan }
function Write-Info { param($Message) Write-Host "[INFO] $Message" -ForegroundColor White }
function Write-Success { param($Message) Write-Host "[OK] $Message" -ForegroundColor Green }
function Write-Warning { param($Message) Write-Host "[WARN] $Message" -ForegroundColor Yellow }

# Check if running as Administrator
$isAdmin = ([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
if (-not $isAdmin) {
    Write-Host "[ERROR] Please run as Administrator" -ForegroundColor Red
    exit 1
}

# Step 1: Create Proxi directory
Write-Step "Creating Proxi directory..."
if (-not (Test-Path $ProxiDir)) {
    New-Item -ItemType Directory -Path $ProxiDir -Force | Out-Null
    Write-Success "Created $ProxiDir"
} else {
    Write-Info "Directory already exists: $ProxiDir"
}

# Step 2: Install Chocolatey if not present
Write-Step "Checking Chocolatey..."
if (-not (Get-Command choco -ErrorAction SilentlyContinue)) {
    Write-Info "Installing Chocolatey..."
    Set-ExecutionPolicy Bypass -Scope Process -Force
    [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
    Invoke-Expression ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
    $env:Path = [System.Environment]::GetEnvironmentVariable("Path", "Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path", "User")
    Write-Success "Chocolatey installed"
} else {
    Write-Success "Chocolatey already installed"
}

# Step 3: Install Python
Write-Step "Installing Python 3.12..."
choco install python312 -y --no-progress 2>$null
$env:Path = [System.Environment]::GetEnvironmentVariable("Path", "Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path", "User")

$pythonVersion = python --version 2>&1
Write-Success "Python version: $pythonVersion"

# Step 4: Install Git
Write-Step "Installing Git..."
choco install git -y --no-progress 2>$null
$env:Path = [System.Environment]::GetEnvironmentVariable("Path", "Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path", "User")
Write-Success "Git installed"

# Step 5: Install Tailscale (optional)
if ($InstallTailscale) {
    Write-Step "Installing Tailscale..."
    $tailscaleUrl = "https://pkgs.tailscale.com/stable/tailscale-setup-latest.exe"
    $tailscaleInstaller = "$env:TEMP\tailscale-setup.exe"
    
    Invoke-WebRequest -Uri $tailscaleUrl -OutFile $tailscaleInstaller
    Start-Process -FilePath $tailscaleInstaller -ArgumentList "/quiet" -Wait
    Write-Success "Tailscale installed"
    Write-Warning "Run 'tailscale up' to authenticate after deployment"
}

# Step 6: Clone/Update repository
Write-Step "Setting up repository..."
Set-Location $ProxiDir

if (Test-Path ".git") {
    Write-Info "Updating existing repository..."
    git fetch origin
    git reset --hard origin/main
} else {
    Write-Warning "Repository not found. Please clone manually:"
    Write-Warning "  git clone https://github.com/yourusername/proxi-ai.git ."
    Write-Warning "Or copy files from your development machine"
}

# Step 7: Create virtual environment
Write-Step "Creating Python virtual environment..."
if (-not (Test-Path "venv")) {
    python -m venv venv
    Write-Success "Virtual environment created"
} else {
    Write-Info "Virtual environment already exists"
}

# Activate venv
& "$ProxiDir\venv\Scripts\Activate.ps1"

# Step 8: Install Python dependencies
Write-Step "Installing Python dependencies..."
if (Test-Path "requirements.txt") {
    pip install --upgrade pip
    pip install -r requirements.txt
    Write-Success "Dependencies installed"
} else {
    Write-Warning "requirements.txt not found"
}

# Step 9: Create environment file
Write-Step "Creating environment file..."
$envContent = @"
# Proxi Backend Configuration
# Generated by deploy-backend.ps1 on $(Get-Date)

GEMINI_API_KEY=$GeminiApiKey
RUNTIME_MODE=REAL
PROXI_HOST=0.0.0.0
PROXI_PORT=8080
"@

$envContent | Out-File -FilePath "$ProxiDir\.env" -Encoding utf8
Write-Success "Environment file created at $ProxiDir\.env"

if ([string]::IsNullOrEmpty($GeminiApiKey)) {
    Write-Warning "GEMINI_API_KEY is empty. Please update .env file with your API key"
}

# Step 10: Create startup script
Write-Step "Creating startup script..."
$startScript = @"
@echo off
cd /d $ProxiDir
call venv\Scripts\activate.bat
echo Starting Proxi Backend...
python -m uvicorn main:app --host 0.0.0.0 --port 8080
"@

$startScript | Out-File -FilePath "$ProxiDir\start-proxi.bat" -Encoding ascii
Write-Success "Startup script created: $ProxiDir\start-proxi.bat"

# Step 11: Create Windows Service (optional)
if ($CreateService) {
    Write-Step "Creating Windows Service..."
    
    # Check if NSSM is installed
    if (-not (Get-Command nssm -ErrorAction SilentlyContinue)) {
        choco install nssm -y --no-progress
        $env:Path = [System.Environment]::GetEnvironmentVariable("Path", "Machine")
    }
    
    # Remove existing service if present
    $serviceName = "ProxiBackend"
    $existingService = Get-Service -Name $serviceName -ErrorAction SilentlyContinue
    if ($existingService) {
        nssm stop $serviceName
        nssm remove $serviceName confirm
    }
    
    # Install service
    nssm install $serviceName "$ProxiDir\start-proxi.bat"
    nssm set $serviceName DisplayName "Proxi AI Backend"
    nssm set $serviceName Description "Proxi headless AI agent backend service"
    nssm set $serviceName Start SERVICE_AUTO_START
    nssm set $serviceName AppDirectory $ProxiDir
    
    Write-Success "Windows Service '$serviceName' created"
    Write-Info "Start with: nssm start $serviceName"
}

# Step 12: Virtual Display Driver info
if ($InstallVirtualDisplay) {
    Write-Step "Virtual Display Driver..."
    Write-Info "Download Virtual Display Driver from:"
    Write-Host "  https://github.com/VirtualDrivers/Virtual-Display-Driver/releases" -ForegroundColor Cyan
    Write-Info "After installation:"
    Write-Info "  1. Run VDC (Virtual Display Control)"
    Write-Info "  2. Click 'Install'"
    Write-Info "  3. Verify in Device Manager -> Display Adapters"
}

# Step 13: Configure Windows Firewall
Write-Step "Configuring Windows Firewall..."
$ruleName = "Proxi Backend API"
$existingRule = Get-NetFirewallRule -DisplayName $ruleName -ErrorAction SilentlyContinue

if (-not $existingRule) {
    New-NetFirewallRule -DisplayName $ruleName `
        -Direction Inbound `
        -Protocol TCP `
        -LocalPort 8080 `
        -Action Allow `
        -Profile Private `
        -Description "Allow Proxi API connections from Tailscale network"
    Write-Success "Firewall rule created (Private profile only)"
} else {
    Write-Info "Firewall rule already exists"
}

# Step 14: Create console session keep-alive script
Write-Step "Creating console session keep-alive script..."
$keepAliveScript = @"
@echo off
REM Keep console session alive when RDP disconnects
REM Add this to Task Scheduler with trigger: On disconnect from user session
(qwinsta | findstr /r "Active" >NUL) || tscon 1 /dest:console
"@

$keepAliveScript | Out-File -FilePath "$ProxiDir\keep-session-alive.bat" -Encoding ascii
Write-Success "Session keep-alive script created"

# Summary
Write-Host ""
Write-Host "=== Deployment Complete ===" -ForegroundColor Green
Write-Host ""
Write-Host "Proxi Directory: $ProxiDir" -ForegroundColor White
Write-Host ""
Write-Host "Next Steps:" -ForegroundColor Yellow
Write-Host "1. Update .env with your GEMINI_API_KEY" -ForegroundColor White
Write-Host "2. Copy your application files to $ProxiDir" -ForegroundColor White
Write-Host "3. Run 'tailscale up' to connect to Tailscale network" -ForegroundColor White
Write-Host "4. Start the server: .\start-proxi.bat" -ForegroundColor White
Write-Host ""
Write-Host "For headless operation:" -ForegroundColor Yellow
Write-Host "- Install Virtual Display Driver" -ForegroundColor White
Write-Host "- Or set up Task Scheduler with keep-session-alive.bat" -ForegroundColor White
Write-Host ""
Write-Host "Get Tailscale IP: tailscale ip -4" -ForegroundColor Cyan
Write-Host ""
